name: Deploy application
 
on:
  push:
    branches: [ master ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: fifsky/ssh-action@master
        with:
         command: |
           cd /var/www/game/gamewatch
           git pull
           npm install
           pm2 restart ./bin/www
         host: ${{ secrets.REMOTE_HOST }}
         user: root
         pass: ${{ secrets.REMOTE_PASSWORD}}
